<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="/assets/css/styles.css"/>
        <link rel="stylesheet" type="text/css" href="/assets/css/jquery-ui.min.css"/>
        <script type="text/javascript" src="/assets/js/jquery-3.1.0.min.js"></script>
        <script type="text/javascript" src="/assets/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/assets/js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="/assets/js/wordlist_english.js"></script>
        <script type="text/javascript" src="/assets/js/bitcoinjs.min.js"></script>
        <script type="text/javascript" src="/assets/js/sjcl-bip39.js"></script>
        <script type="text/javascript" src="/assets/js/jsbip39.js"></script>
        <script type="text/javascript" src="/assets/js/qrcode.js"></script>
        <script type="text/javascript" src="/assets/js/scripts.js"></script>
    </head>