<?php echo $this->fetch('head.phtml'); ?>
<?php echo $this->fetch('header.phtml'); ?>

<h1>Create a new transaction</h1>
<div>
    <span id="message"></span>
    <div class="form-group">
        <input class="form-control" id="qrcode_address" type="text" value="" placeholder="To Address" />
    </div>
    <div class="form-group">
        <input class="form-control" id="qrcode_amount" type="text" value="" placeholder="Amount in Satoshis">
    </div>
    <div class="form-group">
        <input class="form-control" id="qrcode_label" type="text" value="" placeholder="Label">
    </div>
    <div class="form-group">
        <input class="form-control" id="qrcode_message" type="text" value="" placeholder="Message">
    </div>

    <button type="button" id="generate_qrcode" class="btn btn-info">Generate QRCode</button>
    <div class="form-group">
        <div id="qrcode"></div>
    </div>
</div>

<script type="text/javascript">

    Wallet.Transaction.Create.init({
        'submitBtnId' : "#generate_qrcode"
    });

</script>