<?php echo $this->fetch('head.phtml'); ?>
<?php echo $this->fetch('header.phtml'); ?>
<?php echo $this->fetch('messages.phtml'); ?>

<h1>Wallet</h1>

<div>
    Used for generating bitcoin wallets client side - nothing is being saved on the server. Library used is bitcoinjs. Source code is also available on github
    <br>
    <!-- Place this tag where you want the button to render. -->
<a class="github-button" href="https://github.com/epson121/btcwallet" data-icon="octicon-star" data-style="mega" data-count-href="/epson121/btcwallet/stargazers" data-count-api="/repos/epson121/btcwallet#stargazers_count" data-count-aria-label="# stargazers on GitHub" aria-label="Star epson121/btcwallet on GitHub">Star</a>
</div>

<?php echo $this->fetch('footer.phtml'); ?>